/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Custom App Fields JSON
   * Provide an array of fields as JSON: [{ name, label, type, objectName? }].
   *
   */
  fieldsJson: string;
  /**
   * Contract Types (Config)
   * Config-provided contract types; overrides manual input if present.
   *
   */
  contractTypesConfig?: string;
}

/**
 * Custom App Field Picker for Status Updates
 *
 * @description Let users pick Custom App fields for updates to Luminance Statuses
 * This object is used to support type hinting.
 */
export const customAppConfigFieldPicker = {
  key: "customAppConfigFieldPicker",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    fieldsJson: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    contractTypesConfig: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Custom App Field Picker for Status Updates DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiCustomAppConfigFieldPicker = (
  stableKey: string,
  values: {
    fieldsJson: { value: string } | TemplateExpression | ConfigVarExpression;
    contractTypesConfig?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "customAppConfigFieldPicker",
      values,
    },
  });
};
