/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Custom Application Connection
   *
   */
  customAppConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Custom App Fields JSON
   * Provide an array of fields as JSON: [{ name, label, type, objectName? }].
   *
   * @example [{\\"name\\":\\"id\\",\\"label\\":\\"ID\\",\\"type\\":\\"string\\",\\"objectName\\":\\"record\\"},{\\"name\\":\\"title\\",\\"label\\":\\"Title\\",\\"type\\":\\"string\\",\\"objectName\\":\\"record\\"}]
   */
  fieldsJson: string;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * Custom App &lt;&gt; Luminance Matters Tag Mapper
 *
 * @description Map fields between your Custom Application and Luminance Matters Tags
 * This object is used to support type hinting.
 */
export const customAppFieldMapping = {
  key: "customAppFieldMapping",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    customAppConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    fieldsJson: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * Custom App &lt;&gt; Luminance Matters Tag Mapper DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiCustomAppFieldMapping = (
  stableKey: string,
  values: {
    customAppConnection: ConfigVarExpression;
    luminanceConnection: ConfigVarExpression;
    fieldsJson: { value: string } | TemplateExpression | ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "customAppFieldMapping",
      values,
    },
  });
};
