/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * HubSpot Connection
   *
   */
  hubspotConnection: Connection;
  /**
   * HubSpot Objects
   * Comma-separated HubSpot object types (e.g., 'contacts, companies, deals').
   *
   */
  hubspotObjects: string;
  /**
   * Contract Types (Config)
   * Config-provided contract types; overrides manual input if present.
   *
   */
  contractTypesConfig?: string;
}

/**
 * HubSpot Field Picker for Status Updates
 *
 * @description Let users pick HubSpot properties for updates to Luminance Statuses
 * This object is used to support type hinting.
 */
export const hubspotConfigFieldPicker = {
  key: "hubspotConfigFieldPicker",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    hubspotConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    hubspotObjects: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    contractTypesConfig: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * HubSpot Field Picker for Status Updates DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiHubspotConfigFieldPicker = (
  stableKey: string,
  values: {
    hubspotConnection: ConfigVarExpression;
    hubspotObjects:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    contractTypesConfig?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "hubspotConfigFieldPicker",
      values,
    },
  });
};
