/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * HubSpot Connection
   *
   */
  hubspotConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * HubSpot Objects
   * Comma-separated HubSpot object types (e.g., 'companies, contacts, deals' or custom object names).
   *
   */
  hubspotObjects: string;
  /**
   * Filter Luminance Tags by hs_\/HS_
   * Only include Luminance annotation types whose names start with hs_ or HS_ (fallback to all if none).
   *
   * @default true
   */
  filterHsOnly?: string;
  /**
   * Property Filter (optional)
   * Filter properties by name or label to reduce list size.
   *
   */
  propertyFilter?: string;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * HubSpot &lt;&gt; Luminance Matters Tag Mapper
 *
 * @description Map fields between HubSpot CRM Objects and Luminance Matters Tags
 * This object is used to support type hinting.
 */
export const hubspotFieldMapping = {
  key: "hubspotFieldMapping",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    hubspotConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    hubspotObjects: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    filterHsOnly: {
      inputType: "string",
      collection: undefined,
      default: `true`,
    },
    propertyFilter: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * HubSpot &lt;&gt; Luminance Matters Tag Mapper DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiHubspotFieldMapping = (
  stableKey: string,
  values: {
    hubspotConnection: ConfigVarExpression;
    luminanceConnection: ConfigVarExpression;
    hubspotObjects:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    filterHsOnly?: { value: string } | TemplateExpression | ConfigVarExpression;
    propertyFilter?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "hubspotFieldMapping",
      values,
    },
  });
};
