/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { selectProject } from "./selectProject";
import { selectFolder } from "./selectFolder";
import { selectWorkflow } from "./selectWorkflow";
import { selectPrismaticInstance } from "./selectPrismaticInstance";
import { salesforceFieldMappingExample } from "./salesforceFieldMappingExample";
import { salesforceConfigFieldPicker } from "./salesforceConfigFieldPicker";
import { hubspotFieldMapping } from "./hubspotFieldMapping";
import { hubspotConfigFieldPicker } from "./hubspotConfigFieldPicker";
import { dynamicsFieldMappingExample } from "./dynamicsFieldMappingExample";
import { dynamicsConfigFieldPicker } from "./dynamicsConfigFieldPicker";
import { notionFieldMappingExample } from "./notionFieldMappingExample";
import { notionConfigFieldPicker } from "./notionConfigFieldPicker";
import { workdayFieldMappingExample } from "./workdayFieldMappingExample";
import { customAppFieldMapping } from "./customAppFieldMapping";
import { customAppConfigFieldPicker } from "./customAppConfigFieldPicker";
import { luminanceCredentialsViewer } from "./luminanceCredentialsViewer";

export default {
  selectProject,
  selectFolder,
  selectWorkflow,
  selectPrismaticInstance,
  salesforceFieldMappingExample,
  salesforceConfigFieldPicker,
  hubspotFieldMapping,
  hubspotConfigFieldPicker,
  dynamicsFieldMappingExample,
  dynamicsConfigFieldPicker,
  notionFieldMappingExample,
  notionConfigFieldPicker,
  workdayFieldMappingExample,
  customAppFieldMapping,
  customAppConfigFieldPicker,
  luminanceCredentialsViewer,
};
