/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
}

/**
 * Luminance OAuth2 Credentials (Read-only)
 *
 * @description Display Client ID and Client Secret from the provided Luminance connection
 * This object is used to support type hinting.
 */
export const luminanceCredentialsViewer = {
  key: "luminanceCredentialsViewer",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
} as const;

/**
 * Luminance OAuth2 Credentials (Read-only) DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiLuminanceCredentialsViewer = (
  stableKey: string,
  values: {
    luminanceConnection: ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "luminanceCredentialsViewer",
      values,
    },
  });
};
