/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Notion Connection
   * Notion OAuth2 connection.
   *
   */
  notionConnection: Connection;
  /**
   * Notion Database ID (optional)
   * Optional: Notion database ID to fetch properties from. If not provided, you can manually enter property names.
   *
   */
  databaseId?: string;
  /**
   * Contract Types (Config)
   * Config-provided contract types; overrides manual input if present.
   *
   */
  contractTypesConfig?: string;
}

/**
 * Notion Field Picker for Status Updates
 *
 * @description Let users pick Notion properties for updates to Luminance Statuses
 * This object is used to support type hinting.
 */
export const notionConfigFieldPicker = {
  key: "notionConfigFieldPicker",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    notionConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    databaseId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    contractTypesConfig: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Notion Field Picker for Status Updates DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiNotionConfigFieldPicker = (
  stableKey: string,
  values: {
    notionConnection: ConfigVarExpression;
    databaseId?: { value: string } | TemplateExpression | ConfigVarExpression;
    contractTypesConfig?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "notionConfigFieldPicker",
      values,
    },
  });
};
