/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Notion Connection
   * Notion OAuth2 connection.
   *
   */
  notionConnection: Connection;
  /**
   * Luminance Connection
   * Luminance API connection.
   *
   */
  luminanceConnection: Connection;
  /**
   * Notion Database ID (optional)
   * Optional: Notion database ID to fetch properties from. If not provided, you can manually enter property names.
   *
   */
  databaseId?: string;
  /**
   * Filter Luminance Tags by notion_\/Notion_
   * Only include Luminance annotation types whose names start with notion_ or Notion_ (fallback to all if none).
   *
   * @default true
   */
  filterNotionOnly?: string;
  /**
   * Property Filter (optional)
   * Filter properties by name to reduce list size (only used if database ID is provided).
   *
   */
  propertyFilter?: string;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * Notion &lt;&gt; Luminance Matters Tag Mapper
 *
 * @description Map fields between Notion Database Properties and Luminance Matters Tags
 * This object is used to support type hinting.
 */
export const notionFieldMappingExample = {
  key: "notionFieldMappingExample",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    notionConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    databaseId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    filterNotionOnly: {
      inputType: "string",
      collection: undefined,
      default: `true`,
    },
    propertyFilter: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * Notion &lt;&gt; Luminance Matters Tag Mapper DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiNotionFieldMappingExample = (
  stableKey: string,
  values: {
    notionConnection: ConfigVarExpression;
    luminanceConnection: ConfigVarExpression;
    databaseId?: { value: string } | TemplateExpression | ConfigVarExpression;
    filterNotionOnly?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    propertyFilter?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "notionFieldMappingExample",
      values,
    },
  });
};
