/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Salesforce Connection
   *
   */
  sfConnection: Connection;
  /**
   * Salesforce Objects
   * Comma-separated object names (e.g., 'Account, Opportunity').
   *
   */
  salesforceObjects?: string;
  /**
   * Salesforce Object IDs\/Names
   * JSON string containing key-value pairs of object IDs mapped to object names (e.g., '[{\\"|key\\"|: \\"|foo\\"|, \\"|value\\"|: \\"|bar\\"|}, {\\"|key\\"|: \\"|baz\\"|, \\"|value\\"|: \\"|5\\"|}]').
   *
   */
  salesforceObjectIdsNames?: string;
  /**
   * Contract Types (Config)
   * Config-provided contract types; overrides manual input if present.
   *
   */
  contractTypesConfig?: string;
  /**
   * Field Filter (optional)
   * Filter fields by name\/label\/object to reduce list size.
   *
   */
  fieldFilter?: string;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * Salesforce Field Picker for Status Updates
 *
 * @description Let users pick Salesforce fields for updates to Salesforce Statuses
 * This object is used to support type hinting.
 */
export const salesforceConfigFieldPicker = {
  key: "salesforceConfigFieldPicker",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    sfConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    salesforceObjects: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    salesforceObjectIdsNames: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    contractTypesConfig: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fieldFilter: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * Salesforce Field Picker for Status Updates DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiSalesforceConfigFieldPicker = (
  stableKey: string,
  values: {
    sfConnection: ConfigVarExpression;
    salesforceObjects?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    salesforceObjectIdsNames?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    contractTypesConfig?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    fieldFilter?: { value: string } | TemplateExpression | ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "salesforceConfigFieldPicker",
      values,
    },
  });
};
