/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Salesforce Connection
   *
   */
  sfConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Salesforce Objects
   * Enter comma-separated object names (e.g., 'Account', 'Account, Opportunity', 'Custom_Object__c').
   *
   */
  salesforceObjects?: string;
  /**
   * Salesforce Object IDs\/Names
   * JSON string containing key-value pairs of object IDs mapped to object names (e.g., '[{\\"|key\\"|: \\"|foo\\"|, \\"|value\\"|: \\"|bar\\"|}, {\\"|key\\"|: \\"|baz\\"|, \\"|value\\"|: \\"|5\\"|}]').
   *
   */
  salesforceObjectIdsNames?: string;
  /**
   * Field Filter (optional)
   * Filter fields by name\/label\/object to reduce list size.
   *
   */
  fieldFilter?: string;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * Salesforce &lt;&gt; Luminance Matters Tag Mapper
 *
 * @description Map fields between Salesforce Objects and Luminance Matters Tags
 * This object is used to support type hinting.
 */
export const salesforceFieldMappingExample = {
  key: "salesforceFieldMappingExample",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    sfConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    salesforceObjects: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    salesforceObjectIdsNames: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    fieldFilter: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * Salesforce &lt;&gt; Luminance Matters Tag Mapper DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiSalesforceFieldMappingExample = (
  stableKey: string,
  values: {
    sfConnection: ConfigVarExpression;
    luminanceConnection: ConfigVarExpression;
    salesforceObjects?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    salesforceObjectIdsNames?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
    fieldFilter?: { value: string } | TemplateExpression | ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "salesforceFieldMappingExample",
      values,
    },
  });
};
