/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Customer ID (optional)
   *
   */
  customerId?: string;
  /**
   * API Base URL (override)
   * Optional. Set if connection lacks apiBaseUrl and invokeUrl is unavailable.
   *
   */
  apiBaseUrl?: string;
  /**
   * Auth Refresh Path (override)
   * Optional. Defaults to \/auth\/refresh.
   *
   */
  authRefreshPath?: string;
}

/**
 * Select Another Instance
 *
 * @description List instances as a dropdown
 * This object is used to support type hinting.
 */
export const selectPrismaticInstance = {
  key: "selectPrismaticInstance",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    customerId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    apiBaseUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    authRefreshPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Select Another Instance DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiSelectPrismaticInstance = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    customerId?: { value: string } | TemplateExpression | ConfigVarExpression;
    apiBaseUrl?: { value: string } | TemplateExpression | ConfigVarExpression;
    authRefreshPath?:
      | { value: string }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "selectPrismaticInstance",
      values,
    },
  });
};
