/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Max Options (optional)
   * Maximum options to render per dropdown (default: 500).
   *
   * @default 500
   */
  maxOptions?: string;
}

/**
 * Workday Strategic Sourcing &lt;&gt; Luminance Matters Tag Mapper
 *
 * @description Map fields between Workday Strategic Sourcing and Luminance Matters Tags
 * This object is used to support type hinting.
 */
export const workdayFieldMappingExample = {
  key: "workdayFieldMappingExample",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "jsonForm",
  inputs: {
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    maxOptions: {
      inputType: "string",
      collection: undefined,
      default: `500`,
    },
  },
} as const;

/**
 * Workday Strategic Sourcing &lt;&gt; Luminance Matters Tag Mapper DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiWorkdayFieldMappingExample = (
  stableKey: string,
  values: {
    luminanceConnection: ConfigVarExpression;
    maxOptions?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "workdayFieldMappingExample",
      values,
    },
  });
};
