/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "luminanceApi",
  public: false,
  signature: "2a7e8e27e31399f7db4d03a2b76be82636639446",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
