/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface CustomAppValues {
  /**
   * Base URL
   * Base URL of your custom application's API.
   *
   * @placeholder https:\/\/api.example.com
   */
  baseUrl: string;
  /**
   * Access Token (Bearer)
   * Bearer token used for authenticating requests to the custom app.
   *
   */
  accessToken: string;
}

/**
 * Custom Application Connection
 *
 * @comments Generic HTTP connection with Base URL and Bearer token
 * This object is used to support type hinting.
 */
export const customApp = {
  key: "customApp",
  perform: (_values: CustomAppValues): Promise<void> => Promise.resolve(),
  inputs: {
    baseUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    accessToken: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Custom Application Connection Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiCustomApp = (
  stableKey: string,
  values: {
    baseUrl: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    accessToken: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "customApp",
      values,
    },
  });
};
