/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { oAuth2 } from "./oAuth2";
import { secretKey } from "./secretKey";
import { customApp } from "./customApp";

export default {
  oAuth2,
  secretKey,
  customApp,
};
