/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface OAuth2Values {
  /**
   * Token URL
   * Token URL.
   *
   * @default https:\/\/<your-domain>.app.luminance.com\/auth\/oauth2\/token
   */
  tokenUrl?: string;
  /**
   * Scopes
   * Space-delimited scopes.
   *
   */
  scopes?: string;
  /**
   * Client ID
   * Client identifier.
   *
   */
  clientId: string;
  /**
   * Client Secret
   * Client secret.
   *
   */
  clientSecret: string;
}

/**
 * OAuth 2.0 Client Credentials
 *
 * @comments
 * This object is used to support type hinting.
 */
export const oAuth2 = {
  key: "oAuth2",
  perform: (_values: OAuth2Values): Promise<void> => Promise.resolve(),
  inputs: {
    tokenUrl: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/<your-domain>.app.luminance.com\/auth\/oauth2\/token`,
    },
    scopes: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    clientId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * OAuth 2.0 Client Credentials Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiOAuth2 = (
  stableKey: string,
  values: {
    tokenUrl?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    scopes?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientId: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientSecret: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "oAuth2",
      values,
    },
  });
};
