/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface SecretKeyValues {
  /**
   * HMAC Secret Key
   *
   * @placeholder HMAC Secret Key
   */
  secretKey: string;
}

/**
 * HMAC Secret Key
 *
 * @comments HMAC Secret Key
 * This object is used to support type hinting.
 */
export const secretKey = {
  key: "secretKey",
  perform: (_values: SecretKeyValues): Promise<void> => Promise.resolve(),
  inputs: {
    secretKey: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * HMAC Secret Key Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const luminanceApiSecretKey = (
  stableKey: string,
  values: {
    secretKey: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "luminanceApi",
          false,
          context.componentRegistry
        );
      },
      key: "secretKey",
      values,
    },
  });
};
