/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface AssignUserValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Project ID.
   *
   */
  projectId: string;
  /**
   * Matter Id
   * Matter ID.
   *
   */
  matterId: string;
  /**
   * Matter Version
   * Matter Version.
   *
   */
  matterVersion: string;
  /**
   * User Id
   * User ID to assign.
   *
   */
  userId: string;
}

/**
 * Assign a user to a matter version
 *
 * @description Assign a user to a specific version of a matter
 */
export const assignUser = {
  key: "assignUser",
  perform: async <TReturn>(values: AssignUserValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.assignUser({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    matterId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    matterVersion: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
