/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BuildMultipartFromBase64Values {
  /**
   * Base64 File
   * Base64 payload or data URI (data:<mime>;base64,<payload>) for the file.
   *
   */
  fileBase64: string;
  /**
   * Filename
   * Filename to include in the multipart part.
   *
   * @default upload.bin
   */
  filename?: string;
  /**
   * Content Type
   * MIME type of the file.
   *
   * @default application\/octet-stream
   */
  contentType?: string;
  /**
   * File Field Name
   * Form field name for the file part.
   *
   * @default file
   */
  fieldName?: string;
  /**
   * Additional Fields
   * Key-value pairs to include as additional form fields.
   *
   */
  additionalFields?: JSONForm;
}

/**
 * Build multipart parts from Base64
 *
 * @description Convert a base64 string (or data URI) into a structure suitable for multipart/form-data
 */
export const buildMultipartFromBase64 = {
  key: "buildMultipartFromBase64",
  perform: async <TReturn>(
    values: BuildMultipartFromBase64Values
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.buildMultipartFromBase64({
      ...values,
    })) as TReturn;
  },
  inputs: {
    fileBase64: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    filename: {
      inputType: "string",
      collection: undefined,
      default: `upload.bin`,
    },
    contentType: {
      inputType: "string",
      collection: undefined,
      default: `application\/octet-stream`,
    },
    fieldName: {
      inputType: "string",
      collection: undefined,
      default: `file`,
    },
    additionalFields: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
    },
  },
} as const;
