/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BuildAnnotationsFromHubSpotMappingValues {
  /**
   * Mappings
   * Array of mapping entries from the configuration variables (expects hubspotField + luminanceFields).
   *
   */
  mappings: JSONForm;
  /**
   * Primary Data (HubSpot properties)
   * HubSpot properties object from a record.
   *
   */
  primaryData: JSONForm;
  /**
   * Secondary Data (HubSpot properties)
   * Optional secondary HubSpot properties object (e.g., associated Company).
   *
   */
  secondaryData?: JSONForm;
  /**
   * Name Prefix
   * Optional. If set, output includes a name with this prefix and a random suffix.
   *
   */
  namePrefix?: string;
  /**
   * Default Currency
   * Default currency code used for currency mappings when unspecified.
   *
   * @default USD
   */
  defaultCurrency?: string;
}

/**
 * Map data between HubSpot and Luminance
 *
 * @description Map HubSpot data into Luminance matter tag content using the configured mapping
 */
export const buildAnnotationsFromHubSpotMapping = {
  key: "buildAnnotationsFromHubSpotMapping",
  perform: async <TReturn>(
    values: BuildAnnotationsFromHubSpotMappingValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.buildAnnotationsFromHubSpotMapping(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    mappings: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    primaryData: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    secondaryData: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
    },
    namePrefix: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    defaultCurrency: {
      inputType: "string",
      collection: undefined,
      default: `USD`,
    },
  },
} as const;
