/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BuildAnnotationsFromNotionMappingValues {
  /**
   * Mappings
   * Array of mapping entries from the configuration variables (expects notionField + luminanceFields).
   *
   */
  mappings: JSONForm;
  /**
   * Notion Page Properties
   * Notion page properties object from a database page.
   *
   */
  notionData: JSONForm;
  /**
   * Name Prefix
   * Optional. If set, output includes a name with this prefix and a random suffix.
   *
   */
  namePrefix?: string;
  /**
   * Default Currency
   * Default currency code used for currency mappings when unspecified.
   *
   * @default USD
   */
  defaultCurrency?: string;
}

/**
 * Map data between Notion and Luminance
 *
 * @description Map Notion database page properties into Luminance matter tag content using the configured mapping
 */
export const buildAnnotationsFromNotionMapping = {
  key: "buildAnnotationsFromNotionMapping",
  perform: async <TReturn>(
    values: BuildAnnotationsFromNotionMappingValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.buildAnnotationsFromNotionMapping(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    mappings: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    notionData: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    namePrefix: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    defaultCurrency: {
      inputType: "string",
      collection: undefined,
      default: `USD`,
    },
  },
} as const;
