/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BuildNotionPropertiesFromLuminanceMappingValues {
  /**
   * Mappings
   * Array of mapping entries from the configuration variables (expects notionField + luminanceFields).
   *
   */
  mappings: JSONForm;
  /**
   * Matter Tags
   * Array of Luminance matter tags\/annotations (can be matterTags, annotations, or required_matter_annotations).
   *
   */
  matterTags: JSONForm;
  /**
   * Notion Name
   * Optional. If set, will be used as the Contract Name title property in Notion.
   *
   */
  notionName?: string;
  /**
   * Default Currency
   * Default currency code used for currency mappings when unspecified.
   *
   * @default USD
   */
  defaultCurrency?: string;
}

/**
 * Map data between Luminance and Notion
 *
 * @description Map Luminance matter tag content into Notion database page properties using the configured mapping
 */
export const buildNotionPropertiesFromLuminanceMapping = {
  key: "buildNotionPropertiesFromLuminanceMapping",
  perform: async <TReturn>(
    values: BuildNotionPropertiesFromLuminanceMappingValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.buildNotionPropertiesFromLuminanceMapping(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    mappings: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    matterTags: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    notionName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    defaultCurrency: {
      inputType: "string",
      collection: undefined,
      default: `USD`,
    },
  },
} as const;
