/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BuildAnnotationsFromDynamicsMappingValues {
  /**
   * Mappings
   * Array of mapping entries from the configuration variables.
   *
   */
  mappings: JSONForm;
  /**
   * Primary Data
   * Primary source object (e.g., opportunities).
   *
   */
  primaryData: JSONForm;
  /**
   * Secondary Data
   * Secondary source object (e.g., accounts).
   *
   */
  secondaryData?: JSONForm;
  /**
   * Data Object
   * Object storing all mapped Dynamics objects (e.g., opportunities, accounts, etc.).
   *
   */
  dataObject?: string;
  /**
   * Name Prefix
   * Optional. If set, output includes a name with this prefix and a random suffix.
   *
   */
  namePrefix?: string;
  /**
   * Default Currency
   * Default currency code used for currency mappings when unspecified.
   *
   * @default USD
   */
  defaultCurrency?: string;
}

/**
 * Map data between Dynamics and Luminance
 *
 * @description Map input data into Luminance matter tag content using the configured mapping
 */
export const buildAnnotationsFromDynamicsMapping = {
  key: "buildAnnotationsFromDynamicsMapping",
  perform: async <TReturn>(
    values: BuildAnnotationsFromDynamicsMappingValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.buildAnnotationsFromDynamicsMapping(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    mappings: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    primaryData: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    secondaryData: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
    },
    dataObject: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    namePrefix: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    defaultCurrency: {
      inputType: "string",
      collection: undefined,
      default: `USD`,
    },
  },
} as const;
