/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */

import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ConvertBinaryToBase64Values {
  /**
   * Binary Data
   * Binary payload to convert. Accepts Buffer, Uint8Array, number[] or string. Objects with a 'data' field are also supported.
   *
   */
  data: string;
  /**
   * Input Encoding (for strings)
   * Encoding of string inputs (e.g., utf8, base64, hex). Ignored for byte arrays.
   *
   */
  inputEncoding?: string;
}

/**
 * Convert Binary to Base64
 *
 * @description Convert binary data (Buffer/bytes/string) to a base64 string
 */
export const convertBinaryToBase64 = {
  key: "convertBinaryToBase64",
  perform: async <TReturn>(
    values: ConvertBinaryToBase64Values
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.convertBinaryToBase64({
      ...values,
    })) as TReturn;
  },
  inputs: {
    data: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    inputEncoding: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;
