/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */

import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateInitialMatterPayloadValues {
  /**
   * Name
   * Name for the matter. It should be unique, so a guid is recommended.
   *
   */
  name: string;
  /**
   * Workflow ID
   * Target workflow.
   *
   */
  workflowId: string;
}

/**
 * Create Initial Matter Payload
 *
 * @description Create a payload for the initial matter creation
 */
export const createInitialMatterPayload = {
  key: "createInitialMatterPayload",
  perform: async <TReturn>(
    values: CreateInitialMatterPayloadValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.createInitialMatterPayload({
      ...values,
    })) as TReturn;
  },
  inputs: {
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    workflowId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
