/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateDocumentLinkValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Document Id
   * Document ID to link to.
   *
   */
  documentId: string;
}

/**
 * Create Document Link
 *
 * @description Build a Luminance platform document link from a document ID
 */
export const createDocumentLink = {
  key: "createDocumentLink",
  perform: async <TReturn>(
    values: CreateDocumentLinkValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.createDocumentLink({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    documentId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
