/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateMatterLinkValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Matter Id
   * Matter ID to link to.
   *
   */
  matterId: string;
}

/**
 * Create Matter Link
 *
 * @description Build a Luminance platform matter link from a matter ID
 */
export const createMatterLink = {
  key: "createMatterLink",
  perform: async <TReturn>(
    values: CreateMatterLinkValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.createMatterLink({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    matterId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
