/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateLuminanceMatterTagPayloadValues {
  /**
   * Tags
   * Array of tag\/type objects (e.g., results from 'Filter Tags'). Must include 'id' and 'type' fields.
   *
   */
  tags: JSONForm;
  /**
   * Mapped Annotations
   * Output from 'Map data between Salesforce and Luminance' (contains required_matter_annotations).
   *
   */
  mappingResults: JSONForm;
  /**
   * Default Currency
   * Currency to apply to money types when missing.
   *
   * @default USD
   */
  defaultCurrency?: string;
}

/**
 * Create Luminance Matter Tag Payload
 *
 * @description Merge mapped annotations with tag types and coerce values to Luminance formats
 */
export const createLuminanceMatterTagPayload = {
  key: "createLuminanceMatterTagPayload",
  perform: async <TReturn>(
    values: CreateLuminanceMatterTagPayloadValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.createLuminanceMatterTagPayload(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    tags: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    mappingResults: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    defaultCurrency: {
      inputType: "string",
      collection: undefined,
      default: `USD`,
    },
  },
} as const;
