/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection, JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateMatterValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Division ID.
   *
   */
  projectId: string;
  /**
   * body
   * Request body as JSON objects.
   *
   */
  body: JSONForm;
}

/**
 * Create a New Matter
 *
 * @description Create a new matter in a Division
 */
export const createMatter = {
  key: "createMatter",
  perform: async <TReturn>(values: CreateMatterValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.createMatter({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    body: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
} as const;
