/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get System Data
 *
 * @description Get System Data
 */
export const get = {
  key: "get",
  perform: async <TReturn>(values: GetValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.get({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
} as const;
