/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetASpecificMatterValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Project ID.
   *
   */
  projectId: string;
  /**
   * Matter Id
   * Matter ID.
   *
   */
  matterId: string;
}

/**
 * Get information about a specific matter
 *
 * @description Get information about a specific matter
 */
export const getASpecificMatter = {
  key: "getASpecificMatter",
  perform: async <TReturn>(
    values: GetASpecificMatterValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getASpecificMatter({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    matterId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
