/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetAnnotationTypesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Limit
   * Maximum number of matter tags that can be retrieved. Use 'null' to get all results.
   *
   */
  limit?: string;
}

/**
 * Get All Matter Tags
 *
 * @description Get All Matter Tags
 */
export const getAnnotationTypes = {
  key: "getAnnotationTypes",
  perform: async <TReturn>(
    values: GetAnnotationTypesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getAnnotationTypes({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;
