/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetDocumentInfoValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Division ID.
   *
   */
  projectId: string;
  /**
   * Document Id
   * Document ID.
   *
   */
  documentId: string;
}

/**
 * Get info on a specific Document
 *
 * @description Get info on a specific Document
 */
export const getDocumentInfo = {
  key: "getDocumentInfo",
  perform: async <TReturn>(values: GetDocumentInfoValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getDocumentInfo({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    documentId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
