/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetProjectsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Limit
   * Maximum number of objects that can be retrieved.
   *
   */
  limit?: string;
  /**
   * Id
   * Division ID.
   *
   */
  id?: string;
}

/**
 * Get All Divisions
 *
 * @description Get All Divisions
 */
export const getProjects = {
  key: "getProjects",
  perform: async <TReturn>(values: GetProjectsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getProjects({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    id: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;
