/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetUsersValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Username
   * Username used in login credentials.
   *
   */
  username?: string;
}

/**
 * Get User by Username
 *
 * @description Get a specific user by their username
 */
export const getUsers = {
  key: "getUsers",
  perform: async <TReturn>(values: GetUsersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getUsers({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    username: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;
