/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetUsersUserIdValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * User Id
   * User ID.
   *
   */
  userId: string;
}

/**
 * Get a User
 *
 * @description Get a specific user
 */
export const getUsersUserId = {
  key: "getUsersUserId",
  perform: async <TReturn>(values: GetUsersUserIdValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getUsersUserId({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    userId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
