/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetVersionsOfAMatterValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Project ID.
   *
   */
  projectId: string;
  /**
   * Matter Id
   * Matter ID.
   *
   */
  matterId: string;
  /**
   * Limit
   * Maximum number of versions that can be retrieved.
   *
   * @default 50
   */
  limit?: string;
}

/**
 * Get all versions of a specific matter
 *
 * @description Get all versions of a specific matter
 */
export const getVersionsOfAMatter = {
  key: "getVersionsOfAMatter",
  perform: async <TReturn>(
    values: GetVersionsOfAMatterValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getVersionsOfAMatter({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    matterId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: `50`,
    },
  },
} as const;
