/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetWorkflowsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Division Id
   * Division ID.
   *
   */
  projectId: string;
}

/**
 * Get All Workflows
 *
 * @description Get All Workflows for a Division
 */
export const getWorkflows = {
  key: "getWorkflows",
  perform: async <TReturn>(values: GetWorkflowsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.getWorkflows({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    projectId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
