/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { get } from "./get";
import { getUsers } from "./getUsers";
import { getUsersUserId } from "./getUsersUserId";
import { getAnnotationTypes } from "./getAnnotationTypes";
import { getProjects } from "./getProjects";
import { getDocument } from "./getDocument";
import { getDocumentInfo } from "./getDocumentInfo";
import { createDocumentLink } from "./createDocumentLink";
import { createMatter } from "./createMatter";
import { uploadToMatter } from "./uploadToMatter";
import { addMatterInfo } from "./addMatterInfo";
import { patchMatterInfo } from "./patchMatterInfo";
import { getASpecificMatter } from "./getASpecificMatter";
import { getVersionsOfAMatter } from "./getVersionsOfAMatter";
import { assignUser } from "./assignUser";
import { createMatterLink } from "./createMatterLink";
import { getWorkflows } from "./getWorkflows";
import { buildAnnotationsFromMapping } from "./buildAnnotationsFromMapping";
import { buildAnnotationsFromDynamicsMapping } from "./buildAnnotationsFromDynamicsMapping";
import { buildAnnotationsFromNotionMapping } from "./buildAnnotationsFromNotionMapping";
import { buildNotionPropertiesFromLuminanceMapping } from "./buildNotionPropertiesFromLuminanceMapping";
import { buildAnnotationsFromHubSpotMapping } from "./buildAnnotationsFromHubSpotMapping";
import { mapSalesforceToLuminance } from "./mapSalesforceToLuminance";
import { mapHubSpotToLuminance } from "./mapHubSpotToLuminance";
import { mapCustomAppToLuminance } from "./mapCustomAppToLuminance";
import { mapDynamicsToLuminance } from "./mapDynamicsToLuminance";
import { mapNotionToLuminance } from "./mapNotionToLuminance";
import { mapWorkdayToLuminance } from "./mapWorkdayToLuminance";
import { postPrismaticWebhook } from "./postPrismaticWebhook";
import { listPrismaticInstances } from "./listPrismaticInstances";
import { filterOutSpecificTags } from "./filterOutSpecificTags";
import { createLuminanceMatterTagPayload } from "./createLuminanceMatterTagPayload";
import { createInitialMatterPayload } from "./createInitialMatterPayload";
import { convertBinaryToBase64 } from "./convertBinaryToBase64";
import { normalizeConfigMappings } from "./normalizeConfigMappings";
import { mapStatusUpdateToConfigVariables } from "./mapStatusUpdateToConfigVariables";
import { buildMultipartFromBase64 } from "./buildMultipartFromBase64";
import { rawRequest } from "./rawRequest";

export default {
  get,
  getUsers,
  getUsersUserId,
  getAnnotationTypes,
  getProjects,
  getDocument,
  getDocumentInfo,
  createDocumentLink,
  createMatter,
  uploadToMatter,
  addMatterInfo,
  patchMatterInfo,
  getASpecificMatter,
  getVersionsOfAMatter,
  assignUser,
  createMatterLink,
  getWorkflows,
  buildAnnotationsFromMapping,
  buildAnnotationsFromDynamicsMapping,
  buildAnnotationsFromNotionMapping,
  buildNotionPropertiesFromLuminanceMapping,
  buildAnnotationsFromHubSpotMapping,
  mapSalesforceToLuminance,
  mapHubSpotToLuminance,
  mapCustomAppToLuminance,
  mapDynamicsToLuminance,
  mapNotionToLuminance,
  mapWorkdayToLuminance,
  postPrismaticWebhook,
  listPrismaticInstances,
  filterOutSpecificTags,
  createLuminanceMatterTagPayload,
  createInitialMatterPayload,
  convertBinaryToBase64,
  normalizeConfigMappings,
  mapStatusUpdateToConfigVariables,
  buildMultipartFromBase64,
  rawRequest,
};
