/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListPrismaticInstancesValues {
  /**
   * Prismatic Connection
   *
   */
  connection: Connection;
  /**
   * Customer ID
   *
   */
  customerId?: string;
}

/**
 * List Prismatic Instances
 *
 * @description List instances, optionally filtered by customer ID
 */
export const listPrismaticInstances = {
  key: "listPrismaticInstances",
  perform: async <TReturn>(
    values: ListPrismaticInstancesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.listPrismaticInstances({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    customerId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;
