/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapCustomAppToLuminanceValues {
  /**
   * Custom Application Connection
   *
   */
  customAppConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Record Endpoint Path
   * Relative path to fetch the record (e.g., \/v1\/records\/123).
   *
   */
  recordEndpoint: string;
  /**
   * Field Mappings
   *
   */
  fieldMappings: string;
}

/**
 * Map Custom App to Luminance
 *
 * @description Map custom application fields to Luminance annotations using field mappings
 */
export const mapCustomAppToLuminance = {
  key: "mapCustomAppToLuminance",
  perform: async <TReturn>(
    values: MapCustomAppToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapCustomAppToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    customAppConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    recordEndpoint: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      endpoint: "/v1/records/123",
      mappings: [
        {
          objectName: "record",
          fieldKey: "title",
          fieldType: "string",
          customAppValue: "Example Title",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
      ],
    },
  },
} as const;
