/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapDynamicsToLuminanceValues {
  /**
   * Dynamics Connection
   *
   */
  dynamicsConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Record ID
   * The ID of the Dynamics record to map (e.g., Opportunity ID, Account ID, etc.).
   *
   */
  recordId: string;
  /**
   * Object Type
   * The Dynamics object type (e.g., 'opportunities', 'accounts', 'custom_objects').
   *
   */
  objectType: string;
  /**
   * Field Mappings
   * Select the field mappings data source to use for mapping fields.
   *
   */
  fieldMappings: string;
}

/**
 * Map Dynamics to Luminance
 *
 * @description Map Dynamics record fields to Luminance annotations using field mappings
 */
export const mapDynamicsToLuminance = {
  key: "mapDynamicsToLuminance",
  perform: async <TReturn>(
    values: MapDynamicsToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapDynamicsToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dynamicsConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    objectType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      recordId: "12345678-1234-1234-1234-123456789012",
      objectType: "opportunities",
      mappings: [
        {
          objectName: "opportunities",
          fieldKey: "opportunityid",
          dynamicsValue: "12345678-1234-1234-1234-123456789012",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
        {
          objectName: "opportunities",
          fieldKey: "name",
          dynamicsValue: "Acme Corp Deal",
          luminanceFieldId: "789",
          annotationId: "012",
        },
      ],
    },
  },
} as const;
