/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapHubSpotToLuminanceValues {
  /**
   * HubSpot Connection
   *
   */
  hubspotConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Record ID
   * The ID of the HubSpot record to map (e.g., dealId, companyId, contactId).
   *
   */
  recordId: string;
  /**
   * Object Type
   * HubSpot object type (e.g., 'deals', 'companies', 'contacts' or custom object name).
   *
   */
  objectType: string;
  /**
   * Field Mappings
   * Select the HubSpot field mappings data source to use for mapping fields.
   *
   */
  fieldMappings: string;
}

/**
 * Map HubSpot to Luminance
 *
 * @description Map HubSpot record properties to Luminance annotations using field mappings
 */
export const mapHubSpotToLuminance = {
  key: "mapHubSpotToLuminance",
  perform: async <TReturn>(
    values: MapHubSpotToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapHubSpotToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    hubspotConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    objectType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      recordId: "123",
      objectType: "deals",
      mappings: [
        {
          objectName: "deals",
          fieldKey: "dealname",
          fieldType: "string",
          hubspotValue: "Acme Renewal",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
      ],
    },
  },
} as const;
