/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapNotionToLuminanceValues {
  /**
   * Notion Connection
   * Notion OAuth2 connection.
   *
   */
  notionConnection: Connection;
  /**
   * Luminance Connection
   * Luminance API connection.
   *
   */
  luminanceConnection: Connection;
  /**
   * Page ID
   * The ID of the Notion page to map (e.g., page ID from a database).
   *
   */
  pageId: string;
  /**
   * Field Mappings
   * Select the field mappings data source to use for mapping fields.
   *
   */
  fieldMappings: string;
}

/**
 * Map Notion to Luminance
 *
 * @description Map Notion database page properties to Luminance annotations using field mappings
 */
export const mapNotionToLuminance = {
  key: "mapNotionToLuminance",
  perform: async <TReturn>(
    values: MapNotionToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapNotionToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    notionConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    pageId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      pageId: "a8aec231-1234-5678-90ab-cdef12345678",
      mappings: [
        {
          notionFieldName: "Document Type",
          notionValue: "Contract",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
        {
          notionFieldName: "Contract Value",
          notionValue: 50000,
          luminanceFieldId: "789",
          annotationId: "012",
        },
      ],
    },
  },
} as const;
