/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapStatusUpdateToConfigVariablesValues {
  /**
   * Status Update JSON
   * Object with keys: document_link, assignee, contract_status.
   *
   */
  payload: JSONForm;
}

/**
 * Map Status Update to Config Variables
 *
 * @description Map document_link, assignee, contract_status to Luminance config variable keys
 */
export const mapStatusUpdateToConfigVariables = {
  key: "mapStatusUpdateToConfigVariables",
  perform: async <TReturn>(
    values: MapStatusUpdateToConfigVariablesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapStatusUpdateToConfigVariables(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    payload: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
} as const;
