/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapSalesforceToLuminanceValues {
  /**
   * Salesforce Connection
   *
   */
  sfConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Record ID
   * The ID of the Salesforce record to map (e.g., Opportunity ID, Account ID, etc.).
   *
   */
  recordId: string;
  /**
   * Object Type
   * The Salesforce object type (e.g., 'Opportunity', 'Account', 'Custom_Object__c').
   *
   */
  objectType: string;
  /**
   * Field Mappings
   * Select the field mappings data source to use for mapping fields.
   *
   */
  fieldMappings: string;
}

/**
 * Map Salesforce to Luminance
 *
 * @description Map Salesforce record fields to Luminance annotations using field mappings
 */
export const mapSalesforceToLuminance = {
  key: "mapSalesforceToLuminance",
  perform: async <TReturn>(
    values: MapSalesforceToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapSalesforceToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    sfConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    objectType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      recordId: "006gK000000MkfYQAS",
      objectType: "Opportunity",
      mappings: [
        {
          objectName: "Opportunity",
          fieldKey: "Id",
          fieldType: "id",
          isCustom: false,
          salesforceValue: "006gK000000MkfYQAS",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
        {
          objectName: "Opportunity",
          fieldKey: "Name",
          fieldType: "string",
          isCustom: false,
          salesforceValue: "Acme Corp Deal",
          luminanceFieldId: "789",
          annotationId: "012",
        },
      ],
    },
  },
} as const;
