/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MapWorkdayToLuminanceValues {
  /**
   * Workday Connection
   *
   */
  workdayConnection: Connection;
  /**
   * Luminance Connection
   *
   */
  luminanceConnection: Connection;
  /**
   * Record Data
   * The Workday record data as a JSON object.
   *
   */
  recordData: string;
  /**
   * Field Mappings
   * Select the field mappings data source to use for mapping fields.
   *
   */
  fieldMappings: string;
}

/**
 * Map Workday Strategic Sourcing to Luminance
 *
 * @description Map Workday Strategic Sourcing record fields to Luminance annotations using field mappings
 */
export const mapWorkdayToLuminance = {
  key: "mapWorkdayToLuminance",
  perform: async <TReturn>(
    values: MapWorkdayToLuminanceValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.mapWorkdayToLuminance({
      ...values,
    })) as TReturn;
  },
  inputs: {
    workdayConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    luminanceConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    recordData: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    fieldMappings: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      mappings: [
        {
          fieldKey: "contractId",
          workdayValue: "12345",
          luminanceFieldId: "2233",
          annotationId: "456",
        },
        {
          fieldKey: "(blank)",
          workdayValue: "",
          luminanceFieldId: "789",
          annotationId: "012",
        },
      ],
    },
  },
} as const;
