/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { JSONForm } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface NormalizeConfigMappingsValues {
  /**
   * Payload
   * Object with a 'mappings' property where values may be JSON strings.
   *
   */
  payload: JSONForm;
  /**
   * Selected Contract Type
   * Contract type to extract mappings for (matches config value).
   *
   */
  selectedContractType: string;
}

/**
 * Normalize Config Mappings
 *
 * @description Parse nested JSON strings under 'mappings' into proper objects
 */
export const normalizeConfigMappings = {
  key: "normalizeConfigMappings",
  perform: async <TReturn>(
    values: NormalizeConfigMappingsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.normalizeConfigMappings({
      ...values,
    })) as TReturn;
  },
  inputs: {
    payload: {
      inputType: "jsonForm",
      collection: undefined,
      default: undefined,
      required: true,
    },
    selectedContractType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;
