/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface PostPrismaticWebhookValues {
  /**
   * Webhook URL
   * Full Prismatic webhook URL.
   *
   */
  webhookUrl: string;
  /**
   * Payload
   * Request body to POST. Typically JSON.
   *
   */
  payload: string;
  /**
   * HMAC Secret Key
   * Connection containing the HMAC secret, same as the HMAC Webhook Trigger.
   *
   */
  secretKey: Connection;
  /**
   * HMAC Header Name
   * Header name to place the computed HMAC value.
   *
   * @default x-hmac-hash
   */
  hmacHeaderName?: string;
  /**
   * HMAC Algorithm
   * Hash algorithm for HMAC. Typically sha256.
   *
   * @default sha256
   */
  hmacAlgorithm?:
    | `blake2b512`
    | `blake2s256`
    | `md4`
    | `md5`
    | `md5-sha1`
    | `ripemd160`
    | `sha1`
    | `sha224`
    | `sha256`
    | `sha3-224`
    | `sha3-256`
    | `sha3-384`
    | `sha3-512`
    | `sha384`
    | `sha512`
    | `sha512-224`
    | `sha512-256`
    | `sm3`
    | `whirlpool`;
  /**
   * Content-Type
   *
   * @default application\/json
   */
  contentType?: string;
  /**
   * Debug
   * If 'true', return computed hash, headers, and body for troubleshooting.
   *
   * @default false
   */
  debug?: string;
}

/**
 * POST to Prismatic Webhook (HMAC)
 *
 * @description POST payloads to a Prismatic-hosted webhook URL with optional HMAC header.
 */
export const postPrismaticWebhook = {
  key: "postPrismaticWebhook",
  perform: async <TReturn>(
    values: PostPrismaticWebhookValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.luminanceApi.postPrismaticWebhook({
      ...values,
    })) as TReturn;
  },
  inputs: {
    webhookUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    payload: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    secretKey: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    hmacHeaderName: {
      inputType: "string",
      collection: undefined,
      default: `x-hmac-hash`,
    },
    hmacAlgorithm: {
      inputType: "string",
      collection: undefined,
      default: `sha256`,
    },
    contentType: {
      inputType: "string",
      collection: undefined,
      default: `application\/json`,
    },
    debug: {
      inputType: "string",
      collection: undefined,
      default: `false`,
    },
  },
} as const;
