/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { hmacWebhookTrigger } from "./hmacWebhookTrigger";
import { oauthBearerTokenTrigger } from "./oauthBearerTokenTrigger";

export default {
  hmacWebhookTrigger,
  oauthBearerTokenTrigger,
};
