/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface OauthBearerTokenTriggerValues {
  /**
   * Luminance Connection
   * Provide the Luminance OAuth2 Client Credentials connection to source the token URL.
   *
   */
  connection: Connection;
}

/**
 * Proxy incoming requests to the Luminance API using the provided Bearer token
 *
 * @description Proxy incoming requests to the Luminance API using the provided Bearer token
 * This object is used to support type hinting.
 */
export const oauthBearerTokenTrigger = {
  key: "oauthBearerTokenTrigger",
  perform: <TReturn>(
    _values: OauthBearerTokenTriggerValues
  ): Promise<TReturn> => Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
} as const;

/**
 * Proxy incoming requests to the Luminance API using the provided Bearer token Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const luminanceApiOauthBearerTokenTrigger = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "luminanceApi",
        false,
        context.componentRegistry
      );
    },
    key: "oauthBearerTokenTrigger",
    values,
  } as const;
};
